name: "Build prod project dependencies"

runs:
  using: "composite"
  steps:
    - name: Build base
      uses: ./.github/workflows/composite/build_base
    - name: Install dev dependencies
      run: poetry install --without dev
      shell: bash
